name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Installation Method
      description: |
        Select the method used to install the software. Knowing the installation method helps diagnose package-specific bugs.
      options:
        - Select one
        - PyPI (via pip)
        - Homebrew
        - Docker
        - Kali repository (via apt)
        - Built from source
        - Other (please specify below)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Software Version
      description: |
        Specify the version of the software you are using. If you are unsure, please type "Unknown."
      placeholder: e.g., v1.2.3
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: |
        Provide a detailed description of the bug. Clearly describe:
        - What you were trying to accomplish
        - What you expected to happen
        - What actually occurred
        - Why you think this is an issue
      placeholder: |
        When doing {action}, the expected result should be {expected result}.
        However, the actual result was {actual result}.
        This behavior is problematic because {reason}.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide a step-by-step guide that someone else can follow to recreate the issue. Include as much detail as possible.
      placeholder: |
        1. Do something
        2. Then do something else
        3. Observe the issue
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen if the bug did not occur.
      placeholder: Describe the expected output or behavior.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened, including any error messages.
      placeholder: Describe the actual output or behavior.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Include any other details you think might be relevant, such as error logs, screenshots, or code snippets.
      placeholder: Additional context, error logs, screenshots, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct Agreement
      description: |
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/sherlock-project/sherlock/blob/master/docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
